# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-redirect-from
- jekyll-feed
- jekyll-include-cache
- jemoji
- jekyll-remote-theme
- jekyll-seo-tag

# Site settings
url: 'https://lisagoh.github.io'
baseurl: ''
title: 'Lisa Goh'
description: 'Cosmology postdoctoral Researcher at the Royal Observatory of Edinburgh'
permalink: pretty
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
repo: "https://github.com/LisaGoh/lisagoh.github.io"
email: "lisa.goh@cea.fr"

# Pagination
# paginate: 5
# paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Research
  url: /research/
- title: Papers
  url: /papers/
- title: CV
  url: /cv/

# Footer nav
navigation_footer:
- title: Created by Lisa Goh

sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# # Collections
# collections:
#   posts:
#     title: Posts
#     output: true
#     description: "My thoughts and ideas"
#     feature_text: |
#       Welcome to my blog
#     feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: post # Set the default layout for posts
#   -
#     scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: page # Set the default layout for pages


social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/lisa-goh-6305101a4/
  GitHub: https://github.com/LisaGoh
  email: lisa.goh@cea.fr 